---
markdown: kramdown
highlighter: rouge
title: Anthony Ozier-Lafontaine
url: https://anthoOzier.github.io
baseurl: '' # /anthoOzier.github.io

author:
  name: AnthoOzier
#  url: https://twitter.com/fongandrewc
paginate: 5

exclude:
- README.md

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll/scholar
- jemoji

sidebar_home_link: true

theme_colors:
  sidebar-bg-color: "#0B1728" 
  sidebar-fg-color: "#FFFFFF"
  link-color: "#268bd2"

sidebar-sticky: true

layout-reverse: false

remote_theme: fongandrew/hydeout

google_analytics: ''
disqus:
  shortname: ''
# theme: jekyll-theme-hydeout # replaced by remote_theme

