lsi: false
safe: true
source: README.md
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
title: Anthony Ozier-Lafontaine
description: I am looking for a Postdoc in Applied Statistics
